spring:
  data:
    redis:
      host: svc.sel5.cloudtype.app
      port: 31288

  jwt:
    secret: sdkfjghsdfkghasdghkdfjsghsdkfjghersiuthdkjsfgbsdkfjgbhdsjkdfhgdfs
    access-token-expiration: 180
    refresh-token-expiration: 300 #5분

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:20049/BOOK_PHARMACY_LOCAL
#    username: root
#    password: deokwon11@
    url: jdbc:mariadb://svc.sel5.cloudtype.app:32449/BOOK_PHARMACY
    username: sa
    password: 12341234
#    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#                show_sql: true
#                format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: gd6NOn0cl6nUBNLoejwS
            client-secret: N7QQwcmdSd
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,birthday
          google:
            client-name: google
            client-id: 625366027924-vr0ufavfb2vjo7e32asnk0no26sa9hdo.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response



logging.level:
  org.hibernate.SQL: debug
  #org.springframework.security: trace
