spring:
  jwt:
    secret: sdkfjghsdfkghasdghkdfjsghsdkfjghersiuthdkjsfgbsdkfjgbhdsjkdfhgdfs

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:20049/BOOK_PHARMACY_LOCAL
#    username: root
#    password: deokwon11@

    url: jdbc:mariadb://localhost:3306/bookpharmacylocaldb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12341234


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#                show_sql: true
#                format_sql: true

logging.level:
  org.hibernate.SQL: debug