spring:
  data:
    redis:
      host: svc.sel5.cloudtype.app
      port: 31288

  jwt:
    secret: sdkfjghsdfkghasdghkdfjsghsdkfjghersiuthdkjsfgbsdkfjgbhdsjkdfhgdfs
    access-token-expiration: 60
    refresh-token-expiration: 300 #5분

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:20049/BOOK_PHARMACY_LOCAL
#    username: root
#    password: deokwon11@
#    url: jdbc:mariadb://svc.sel5.cloudtype.app:32449/BOOK_PHARMACY
#    username: sa
#    password: 12341234
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#                show_sql: true
#                format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.springframework.security: trace
