version: "3"
services:
  backend:
    build: .
    ports:
      - "8081:8080"
    container_name: spring-blue
    networks:
      - my-network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge