version: "3"
services:
  backend:
    build: .
    ports:
      - "8082:8080"
    container_name: spring-green
    networks:
      - my-network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge