spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://svc.sel5.cloudtype.app:32449/BOOK_PHARMACY
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: sa
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

