spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://svc.sel5.cloudtype.app:32449/BOOK_PHARMACY
    url: jdbc:mariadb://mariadb:3306
    username: sa
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

